import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import {SliderData} from '../components/SliderData'
import Slider from '../components/Slider'
import Instagram from '../components/Instagram'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Sebastian Flores cv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Sebastián Flores' message="Student of informatics engineering." mail="floresirahetasebastian@hotmail.com" phone="+503 7210-7214" place="San Salvador, San Salvador"/>
      {/* 
          <Slider slides={SliderData}/> 
          <Instagram />
      */}
      

    </div>
  )
}
