import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import {SliderData} from '../components/SliderData'
import Slider from '../components/Slider'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Sebastián Flores Portfolio' message="This is just a little recap of the projects I've been working on."/>
      <Slider slides={SliderData}/>

    </div>
  )
}
