import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import {SliderData} from '../components/SliderData'
import Slider from '../components/Slider'
import Instagram from '../components/Instagram'
import AboutM from '../components/AboutMe'
import Software from '../components/LanguagesSkills'
import Softskill from '../components/SoftSkills'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Sebastian Flores cv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero greeting={"Hello 👋 my name is"} heading={"Sebastián Flores" } message="Front-end dev" mail="floresirahetasebastian@hotmail.com" phone="+503 7210-7214" place="San Salvador, San Salvador"/>
      {/* 
      <Instagram />
    */}
      <AboutM />
      <Slider slides={SliderData}/> 
      <Software/>
      <Softskill/>
      <footer>
        <Footer />
      </footer>
    </div>
    
  )
}
